### Warm Up- Numpy and Functions

1. Create a new .py file called number_finder.

2. In the number_finder.py file create 2 functions.  The first function (called prime_finder) will select only the prime #'s from a given numpy array.  The second function (called fibonacci_finder) will select only the Fibonacci numbers from a given numpy array.
 
3. Now open a new jupyter notebook.  

4. In your jupyter notebook import number_finder.

5.  Next create an array called numbers that contains 100 random numbers.

6.  Apply both number_finder functions to the array you created to find the prime and fibonacci numbers contained in your array.

BONUS

Create an additional function to find the tribonacci numbers in your array.

In [22]:
import number_finder as nf
import numpy as np

In [23]:
numbers = np.random.randint(2, 300, size=(50,50))
print(numbers)

[[246 118 208 ... 251 286 102]
 [ 52   7 265 ... 218 152 240]
 [111 222 220 ... 241 235 156]
 ...
 [ 25 256  92 ... 215  59  57]
 [219 213 127 ... 254 219 206]
 [236 287  98 ...  16 152 291]]


In [24]:
array_primes = nf.prime_finder(numbers)
print(array_primes)

[[  0   0   0 ... 251   0   0]
 [  0   7   0 ...   0   0   0]
 [  0   0   0 ... 241   0   0]
 ...
 [  0   0   0 ...   0  59   0]
 [  0   0 127 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [25]:
array_primes_2 = nf.prime_finder_array(numbers)
print(array_primes_2)

[[  0   0   0 ... 251   0   0]
 [  0   7   0 ...   0   0   0]
 [  0   0   0 ... 241   0   0]
 ...
 [  0   0   0 ...   0  59   0]
 [  0   0 127 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [26]:
print(np.array_equal(array_primes, array_primes_2))

True


In [21]:
print(nf.fibonacci_finder(numbers))

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0 34  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
